// angular-multiselect/src/app/components/multi-select/multi-select-dropdown.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  OnInit,
  OnChanges,
  SimpleChanges,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { MultiSelectItem } from "../../models/multi-select-item.interface";

@Component({
  selector: "app-multi-select-dropdown",
  standalone: true,
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="dropdown-content">
      <!-- Search Input -->
      <div class="search-container">
        <input
          type="text"
          class="search-input"
          [placeholder]="searchPlaceholder"
          [(ngModel)]="searchValue"
          (input)="onSearchChange()"
          [style.font-family]="'Poppins, sans-serif'"
        />
      </div>

      <!-- Options List -->
      <div class="options-container">
        <div
          *ngFor="let option of filteredOptions; trackBy: trackOption"
          class="option-item"
          (click)="onOptionClick(option)"
        >
          <div class="option-checkbox">
            <input
              type="checkbox"
              [id]="'option-' + option.id"
              [checked]="isSelected(option)"
              [disabled]="option.disabled"
              class="checkbox-input"
            />
            <div class="checkbox-custom" [class.checked]="isSelected(option)">
              <svg
                *ngIf="isSelected(option)"
                class="checkbox-icon"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
          </div>
          <span
            class="option-label"
            [style.font-family]="'Poppins, sans-serif'"
            [class.disabled]="option.disabled"
          >
            {{ option.label }}
          </span>
        </div>

        <!-- Create New Option -->
        <div
          *ngIf="shouldShowCreateOption"
          class="option-item create-option"
          (click)="onCreateClick()"
        >
          <span
            class="create-option-text"
            [style.font-family]="'Poppins, sans-serif'"
          >
            Create tag "{{ searchValue }}"
          </span>
        </div>

        <!-- No Options Message -->
        <div
          *ngIf="filteredOptions.length === 0 && !shouldShowCreateOption"
          class="no-options"
          [style.font-family]="'Poppins, sans-serif'"
        >
          No options found
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .dropdown-content {
        background: white;
        border: 1px solid #008bc9;
        border-radius: 4px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        max-height: 240px;
        overflow: hidden;
        display: flex;
        flex-direction: column;
        min-width: 200px;
        max-width: 400px;
      }

      .search-container {
        padding: 8px;
        border-bottom: 1px solid #e5e7eb;
      }

      .search-input {
        width: 100%;
        padding: 8px 12px;
        border: 1px solid #d1d5db;
        border-radius: 4px;
        font-size: 12px;
        font-weight: 400;
        letter-spacing: 0.429px;
        outline: none;
        transition: border-color 0.2s ease;
      }

      .search-input:focus {
        border-color: #008bc9;
      }

      .search-input::placeholder {
        color: #bababa;
      }

      .options-container {
        flex: 1;
        overflow-y: auto;
        max-height: 184px;
      }

      .option-item {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 8px 12px;
        cursor: pointer;
        transition: background-color 0.2s ease;
      }

      .option-item:hover {
        background-color: #f3f4f6;
      }

      .option-checkbox {
        position: relative;
        display: flex;
        align-items: center;
      }

      .checkbox-input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
      }

      .checkbox-custom {
        width: 16px;
        height: 16px;
        border: 1px solid #d1d5db;
        border-radius: 2px;
        display: flex;
        align-items: center;
        justify-content: center;
        background: white;
        transition: all 0.2s ease;
      }

      .checkbox-custom.checked {
        background-color: #008bc9;
        border-color: #008bc9;
      }

      .checkbox-icon {
        width: 12px;
        height: 12px;
        color: white;
      }

      .option-label {
        flex: 1;
        font-size: 12px;
        font-weight: 400;
        letter-spacing: 0.429px;
        color: #212529;
      }

      .option-label.disabled {
        color: #9ca3af;
        cursor: not-allowed;
      }

      .create-option {
        border-top: 1px solid #e5e7eb;
        background-color: #f9fafb;
      }

      .create-option:hover {
        background-color: #f3f4f6;
      }

      .create-option-text {
        font-size: 12px;
        font-weight: 400;
        letter-spacing: 0.429px;
        color: #4c5564;
      }

      .no-options {
        padding: 16px 12px;
        text-align: center;
        font-size: 12px;
        color: #9ca3af;
        font-style: italic;
      }
    `,
  ],
})
export class MultiSelectDropdownComponent implements OnInit, OnChanges {
  @Input() options: MultiSelectItem[] = [];
  @Input() selectedItems: MultiSelectItem[] = [];
  @Input() searchPlaceholder: string = "Search tags";

  @Output() selectionChange = new EventEmitter<{
    item: MultiSelectItem;
    isSelected: boolean;
  }>();
  @Output() createNew = new EventEmitter<string>();

  searchValue: string = "";
  filteredOptions: MultiSelectItem[] = [];

  ngOnInit(): void {
    this.updateFilteredOptions();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["options"] || changes["selectedItems"]) {
      this.updateFilteredOptions();
    }
  }

  onSearchChange(): void {
    this.updateFilteredOptions();
  }

  private updateFilteredOptions(): void {
    if (!this.searchValue.trim()) {
      this.filteredOptions = this.options.slice();
    } else {
      const searchLower = this.searchValue.toLowerCase();
      this.filteredOptions = this.options.filter((option) =>
        option.label.toLowerCase().includes(searchLower),
      );
    }
  }

  get shouldShowCreateOption(): boolean {
    if (!this.searchValue.trim()) return false;

    // Check if search exactly matches any existing option
    const exactMatch = this.options.some(
      (option) =>
        option.label.toLowerCase() === this.searchValue.toLowerCase().trim(),
    );

    return !exactMatch;
  }

  isSelected(option: MultiSelectItem): boolean {
    return this.selectedItems.some((item) => item.id === option.id);
  }

  onOptionClick(option: MultiSelectItem): void {
    if (option.disabled) return;

    const isSelected = this.isSelected(option);
    this.selectionChange.emit({ item: option, isSelected });
  }

  onCreateClick(): void {
    if (this.searchValue.trim()) {
      this.createNew.emit(this.searchValue.trim());
    }
  }

  trackOption(index: number, option: MultiSelectItem): any {
    return option.id;
  }
}

// src/components/MultiSelect/MultiSelectDropdown.tsx
import * as React from "react";
import { ChevronDown, Check } from "lucide-react";
import { cn } from "@/lib/utils";
import type { MultiSelectItem } from "./MultiSelect";

interface MultiSelectDropdownProps {
  options: MultiSelectItem[];
  selectedItems: MultiSelectItem[];
  onSelectionChange: (item: MultiSelectItem, isSelected: boolean) => void;
  searchValue: string;
  onSearchChange: (value: string) => void;
  searchPlaceholder?: string;
  className?: string;
  onCreateNew?: (label: string) => void;
}

/**
 * MultiSelectDropdown Component
 *
 * Internal dropdown component for the MultiSelect. Handles search and option selection.
 */
export const MultiSelectDropdown = React.forwardRef<
  HTMLDivElement,
  MultiSelectDropdownProps
>(
  (
    {
      options,
      selectedItems,
      onSelectionChange,
      searchValue,
      onSearchChange,
      searchPlaceholder = "Search tags",
      className,
      onCreateNew,
      ...props
    },
    ref,
  ) => {
    const selectedIds = React.useMemo(
      () => new Set(selectedItems.map((item) => item.id)),
      [selectedItems],
    );

    const filteredOptions = React.useMemo(() => {
      if (!searchValue) return options;
      return options.filter((option) =>
        option.label.toLowerCase().includes(searchValue.toLowerCase()),
      );
    }, [options, searchValue]);

    // Check if there's an exact match for the search value
    const hasExactMatch = React.useMemo(() => {
      if (!searchValue.trim()) return true;
      return options.some(
        (option) => option.label.toLowerCase() === searchValue.toLowerCase(),
      );
    }, [options, searchValue]);

    // Show create option if there's search text and no exact match
    const showCreateOption =
      searchValue.trim() && !hasExactMatch && onCreateNew;

    return (
      <div
        ref={ref}
        className={cn("flex w-[411px] flex-col bg-white shadow-lg", className)}
        {...props}
      >
        {/* Search Box */}
        <div className="flex min-h-[32px] items-center border-t border-r border-l border-[#008BC9] bg-white rounded-t">
          <div className="flex flex-1 items-center px-2 py-1.5">
            <input
              type="text"
              value={searchValue}
              onChange={(e) => onSearchChange(e.target.value)}
              placeholder={searchPlaceholder}
              className="flex-1 bg-transparent text-xs font-poppins text-[#4C5564] placeholder:text-[#BABABA] tracking-[0.429px] border-none outline-none"
              autoFocus
            />
          </div>
          <div className="flex items-center justify-center px-2 py-1">
            <ChevronDown className="h-4 w-4 text-[#545454]" />
          </div>
        </div>

        {/* Separator */}
        <div className="h-px bg-[#E6E6E6]" />

        {/* Options List */}
        <div className="flex flex-col border-r border-b border-l border-[#008BC9] bg-white rounded-b-lg py-1 max-h-[200px] overflow-y-auto">
          {filteredOptions.length === 0 && !showCreateOption ? (
            <div className="px-2 py-2 text-xs text-[#BABABA] font-poppins">
              {searchValue
                ? "No matching options found"
                : "No options available"}
            </div>
          ) : (
            <>
              {filteredOptions.map((option) => {
                const isSelected = selectedIds.has(option.id);
                const isDisabled = option.disabled;

                return (
                  <div
                    key={option.id}
                    className={cn(
                      "flex items-center gap-2 px-2 py-2 cursor-pointer transition-colors",
                      isDisabled
                        ? "opacity-50 cursor-not-allowed"
                        : "hover:bg-gray-50",
                    )}
                    onClick={() => {
                      if (!isDisabled) {
                        onSelectionChange(option, isSelected);
                      }
                    }}
                  >
                    {/* Custom Checkbox */}
                    <div className="flex w-5 items-center justify-center">
                      <div
                        className={cn(
                          "relative h-[18px] w-[18px] rounded-sm border flex items-center justify-center transition-colors",
                          isSelected
                            ? "bg-[#545454] border-[#545454]"
                            : "bg-white border-[#BABABA]",
                          isDisabled && "opacity-50",
                        )}
                      >
                        {isSelected && (
                          <Check
                            className="h-3 w-3 text-white"
                            strokeWidth={3}
                          />
                        )}
                      </div>
                    </div>

                    {/* Label */}
                    <span
                      className={cn(
                        "flex-1 text-xs font-medium font-poppins tracking-[0.429px]",
                        isDisabled ? "text-[#BABABA]" : "text-[#4C5564]",
                      )}
                    >
                      {option.label}
                    </span>
                  </div>
                );
              })}

              {/* Create New Option */}
              {showCreateOption && (
                <div
                  className="flex items-center justify-start gap-2 px-2 py-2 cursor-pointer transition-colors hover:bg-gray-50 self-stretch"
                  onClick={() => {
                    onCreateNew(searchValue.trim());
                    onSearchChange("");
                  }}
                >
                  <span className="flex-1 text-xs font-normal text-[#4C5564] font-poppins tracking-[0.429px]">
                    Create tag "{searchValue}"
                  </span>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    );
  },
);

MultiSelectDropdown.displayName = "MultiSelectDropdown";
