// src/components/MultiSelect/MultiSelect.tsx
import * as React from "react";
import { Plus } from "lucide-react";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";
import { Tag } from "../Tag";
import { Button } from "../ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "../ui/popover";
import { MultiSelectDropdown } from "./MultiSelectDropdown";

const multiSelectVariants = cva("flex w-full gap-1", {
  variants: {
    orientation: {
      horizontal: "flex-row items-start",
      vertical: "flex-col",
    },
    size: {
      sm: "text-xs",
      default: "text-sm",
      lg: "text-base",
    },
  },
  defaultVariants: {
    orientation: "horizontal",
    size: "default",
  },
});

export interface MultiSelectItem {
  id: string | number;
  label: string;
  disabled?: boolean;
}

export interface SelectedItemUIProps {
  item: MultiSelectItem;
  onRemove?: () => void;
  removable?: boolean;
}

export interface MultiSelectProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof multiSelectVariants> {
  /**
   * Label displayed next to the component
   */
  label?: string;
  /**
   * Position of the label relative to the input
   */
  labelPosition?: "left" | "right";
  /**
   * Currently selected items
   */
  value: MultiSelectItem[];
  /**
   * Available options to select from
   */
  options: MultiSelectItem[];
  /**
   * Callback when items are added or removed
   */
  onChange: (items: MultiSelectItem[]) => void;
  /**
   * Custom component to render each selected item
   * Receives item, onRemove, and removable props
   */
  selectedItemUI?: React.ComponentType<SelectedItemUIProps>;
  /**
   * Text displayed on the add button
   */
  addButtonText?: string;
  /**
   * Placeholder text for the search input
   */
  searchPlaceholder?: string;
  /**
   * Maximum width of the component
   */
  maxWidth?: string;
  /**
   * Whether the component is disabled
   */
  disabled?: boolean;
  /**
   * Whether to show the add button
   */
  showAddButton?: boolean;
  /**
   * Whether items can be removed
   */
  allowRemove?: boolean;
  /**
   * Whether the add button should take full width on its own line
   */
  fullWidthButton?: boolean;
}

/**
 * MultiSelect Component
 *
 * A modern, accessible multi-select component with tags and dropdown functionality.
 * Built with React, TypeScript, and Tailwind CSS.
 *
 * @example
 * ```tsx
 * const [selectedItems, setSelectedItems] = useState<MultiSelectItem[]>([]);
 * const options = [
 *   { id: 1, label: "Option 1" },
 *   { id: 2, label: "Option 2" },
 * ];
 *
 * <MultiSelect
 *   label="Select items"
 *   value={selectedItems}
 *   options={options}
 *   onChange={setSelectedItems}
 * />
 * ```
 */
// Default selected item component
const DefaultSelectedItemUI: React.FC<SelectedItemUIProps> = ({
  item,
  onRemove,
  removable,
}) => (
  <Tag
    label={item.label}
    onRemove={onRemove}
    removable={removable}
    variant="default"
  />
);

export const MultiSelect = React.forwardRef<HTMLDivElement, MultiSelectProps>(
  (
    {
      className,
      orientation,
      size,
      label = "Tags",
      labelPosition = "left",
      value = [],
      options = [],
      onChange,
      selectedItemUI: SelectedItemComponent = DefaultSelectedItemUI,
      addButtonText = "Add Tags",
      searchPlaceholder = "Search tags",
      maxWidth = "568px",
      disabled = false,
      showAddButton = true,
      allowRemove = true,
      fullWidthButton = false,
      ...props
    },
    ref,
  ) => {
    const [open, setOpen] = React.useState(false);
    const [searchValue, setSearchValue] = React.useState("");

    const handleSelectionChange = React.useCallback(
      (item: MultiSelectItem, isSelected: boolean) => {
        if (disabled) return;

        let newItems: MultiSelectItem[];
        if (isSelected) {
          // Remove item
          newItems = value.filter((existing) => existing.id !== item.id);
        } else {
          // Add item
          const itemExists = value.some((existing) => existing.id === item.id);
          if (!itemExists) {
            newItems = [...value, item];
          } else {
            newItems = value;
          }
        }
        onChange(newItems);
      },
      [value, onChange, disabled],
    );

    const handleCreateNew = React.useCallback(
      (label: string) => {
        if (disabled) return;

        // Create new item with unique ID (timestamp + random to avoid collisions)
        const newItem: MultiSelectItem = {
          id: `new-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
          label: label.trim(),
        };

        // Add to selected items
        const newItems = [...value, newItem];
        onChange(newItems);

        // Close dropdown
        setOpen(false);
      },
      [value, onChange, disabled],
    );

    const handleRemove = React.useCallback(
      (itemToRemove: MultiSelectItem) => {
        if (disabled || !allowRemove) return;
        const newItems = value.filter((item) => item.id !== itemToRemove.id);
        onChange(newItems);
      },
      [value, onChange, disabled, allowRemove],
    );

    const handleOpenChange = React.useCallback(
      (newOpen: boolean) => {
        if (disabled) return;
        setOpen(newOpen);
        if (!newOpen) {
          setSearchValue("");
        }
      },
      [disabled],
    );

    // Calculate available options (excluding already selected items)
    const availableOptions = React.useMemo(() => {
      return options.filter((option) => !option.disabled);
    }, [options]);

    // Label component
    const LabelComponent = label ? (
      <div
        className="flex min-w-[153px] items-start"
        style={{ padding: "7px 8px" }}
      >
        <span className="text-xs font-semibold text-[#545454] font-poppins tracking-[0.429px]">
          {label}
        </span>
      </div>
    ) : null;

    // Value container with selected items and add button
    const ValueContainer =
      showAddButton && availableOptions.length > 0 ? (
        <div className="relative">
          {/* Fixed positioning anchor - invisible element at top-left of input area */}
          <Popover open={open} onOpenChange={handleOpenChange}>
            <PopoverTrigger asChild>
              <div className="absolute top-0 left-2 w-1 h-1 opacity-0 pointer-events-none" />
            </PopoverTrigger>
            <PopoverContent
              className="w-auto p-0 border-0 bg-transparent shadow-none"
              align="start"
              side="bottom"
              sideOffset={-8}
              alignOffset={0}
            >
              <MultiSelectDropdown
                options={availableOptions}
                selectedItems={value}
                onSelectionChange={handleSelectionChange}
                searchValue={searchValue}
                onSearchChange={setSearchValue}
                searchPlaceholder={searchPlaceholder}
                onCreateNew={handleCreateNew}
              />
            </PopoverContent>
          </Popover>

          {/* Content container */}
          <div
            className={cn(
              "flex flex-1 min-h-[32px] pl-2",
              fullWidthButton
                ? "flex-col gap-2"
                : "flex-wrap items-center gap-2",
            )}
          >
            {/* Selected Items */}
            {fullWidthButton ? (
              <div className="flex flex-col gap-2 w-full">
                {value.map((item) => (
                  <div key={item.id} onClick={(e) => e.stopPropagation()}>
                    <SelectedItemComponent
                      item={item}
                      onRemove={
                        allowRemove ? () => handleRemove(item) : undefined
                      }
                      removable={allowRemove && !disabled}
                    />
                  </div>
                ))}
              </div>
            ) : (
              value.map((item) => (
                <div key={item.id} onClick={(e) => e.stopPropagation()}>
                  <SelectedItemComponent
                    item={item}
                    onRemove={
                      allowRemove ? () => handleRemove(item) : undefined
                    }
                    removable={allowRemove && !disabled}
                  />
                </div>
              ))
            )}

            {/* Add Button - now just triggers the popup */}
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={disabled}
              onClick={() => !disabled && setOpen(!open)}
              className={cn(
                "bg-[#FFF] px-2 py-0.5 text-xs font-semibold text-[#006CAB] hover:bg-blue-50 hover:text-blue-800 border-0 shadow-none rounded font-poppins tracking-[0.429px] disabled:opacity-50",
                fullWidthButton ? "w-full h-auto p-2 justify-start" : "h-6",
              )}
            >
              {addButtonText}
              <Plus className="h-3 w-3" />
            </Button>
          </div>
        </div>
      ) : (
        <div
          className={cn(
            "flex flex-1 min-h-[32px] pl-2",
            fullWidthButton ? "flex-col gap-2" : "flex-wrap items-center gap-2",
          )}
        >
          {/* Selected Items */}
          {fullWidthButton ? (
            <div className="flex flex-col gap-2 w-full">
              {value.map((item) => (
                <SelectedItemComponent
                  key={item.id}
                  item={item}
                  onRemove={allowRemove ? () => handleRemove(item) : undefined}
                  removable={allowRemove && !disabled}
                />
              ))}
            </div>
          ) : (
            value.map((item) => (
              <SelectedItemComponent
                key={item.id}
                item={item}
                onRemove={allowRemove ? () => handleRemove(item) : undefined}
                removable={allowRemove && !disabled}
              />
            ))
          )}

          {/* Add Button (without dropdown) */}
          {showAddButton && (
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={true}
              className={cn(
                "bg-[#FFF] px-2 py-0.5 text-xs font-semibold text-[#006CAB] hover:bg-blue-50 hover:text-blue-800 border-0 shadow-none rounded font-poppins tracking-[0.429px] opacity-50",
                fullWidthButton ? "w-full h-auto p-2 justify-start" : "h-6",
              )}
            >
              {addButtonText}
              <Plus className="h-3 w-3" />
            </Button>
          )}
        </div>
      );
    return (
      <div
        className={cn(
          multiSelectVariants({ orientation, size }),
          "h-auto flex-grow-0",
          disabled && "opacity-50 pointer-events-none",
          className,
        )}
        style={{ maxWidth }}
        ref={ref}
        {...props}
      >
        {labelPosition === "left" ? (
          <>
            {LabelComponent}
            {ValueContainer}
          </>
        ) : (
          <>
            {ValueContainer}
            {LabelComponent}
          </>
        )}
      </div>
    );
  },
);

MultiSelect.displayName = "MultiSelect";

// angular-multiselect/src/app/components/multi-select/multi-select.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  TemplateRef,
  ContentChild,
  ViewChild,
  ElementRef,
  ChangeDetectorRef,
  OnDestroy,
  forwardRef,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";
import { Subject } from "rxjs";
import { takeUntil } from "rxjs/operators";

import {
  MultiSelectItem,
  MultiSelectOrientation,
  MultiSelectSize,
  SelectedItemUIContext,
} from "../../models/multi-select-item.interface";
import { TagComponent } from "../tag/tag.component";
import { MultiSelectDropdownComponent } from "./multi-select-dropdown.component";

@Component({
  selector: "app-multi-select",
  standalone: true,
  imports: [CommonModule, TagComponent, MultiSelectDropdownComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => MultiSelectComponent),
      multi: true,
    },
  ],
  template: `
    <div
      [class]="getContainerClasses()"
      [style.max-width]="maxWidth"
      [style.font-family]="'Poppins, sans-serif'"
    >
      <!-- Label -->
      <div
        *ngIf="label"
        class="label-container"
        [style.padding]="'7px 8px'"
        [style.min-width]="'153px'"
      >
        <span class="label-text">{{ label }}</span>
      </div>

      <!-- Value Container -->
      <div class="value-container">
        <!-- Selected Items -->
        <div [class]="getSelectedItemsClasses()">
          <ng-container *ngFor="let item of value; trackBy: trackSelectedItem">
            <!-- Custom Template -->
            <ng-container
              *ngIf="selectedItemTemplate; else defaultSelectedItem"
            >
              <ng-container
                *ngTemplateOutlet="
                  selectedItemTemplate;
                  context: {
                    $implicit: item,
                    removable: allowRemove && !disabled,
                    onRemove: getRemoveFunction(item),
                  }
                "
              >
              </ng-container>
            </ng-container>

            <!-- Default Tag -->
            <ng-template #defaultSelectedItem>
              <app-tag
                [label]="item.label"
                [removable]="allowRemove && !disabled"
                [disabled]="disabled"
                (remove)="handleRemove(item)"
                variant="default"
              ></app-tag>
            </ng-template>
          </ng-container>
        </div>

        <!-- Add Button with Dropdown -->
        <div
          *ngIf="showAddButton && !disabled && availableOptions.length > 0"
          class="add-button-container"
          [class.full-width]="fullWidthButton"
        >
          <div class="dropdown-wrapper" #dropdownWrapper>
            <!-- Positioning anchor -->
            <div class="dropdown-anchor" #dropdownAnchor></div>

            <!-- Add Button -->
            <button
              type="button"
              class="add-button"
              [class.full-width-button]="fullWidthButton"
              (click)="toggleDropdown()"
              [attr.aria-expanded]="isOpen"
              [attr.aria-haspopup]="true"
              [style.font-family]="'Poppins, sans-serif'"
            >
              <svg
                class="add-icon"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 4v16m8-8H4"
                />
              </svg>
              {{ addButtonText }}
            </button>

            <!-- Dropdown -->
            <div
              *ngIf="isOpen"
              class="dropdown-overlay"
              (click)="closeDropdown()"
            ></div>
            <div
              *ngIf="isOpen"
              class="dropdown-content"
              [style.position]="'fixed'"
              [style.z-index]="'1000'"
              #dropdownContent
            >
              <app-multi-select-dropdown
                [options]="availableOptions"
                [selectedItems]="value"
                [searchPlaceholder]="searchPlaceholder"
                (selectionChange)="handleSelectionChange($event)"
                (createNew)="handleCreateNew($event)"
              ></app-multi-select-dropdown>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .multi-select-container {
        display: flex;
        width: 100%;
        gap: 4px;
      }

      .multi-select-horizontal {
        flex-direction: row;
        align-items: flex-start;
      }

      .multi-select-vertical {
        flex-direction: column;
      }

      .label-container {
        display: flex;
        align-items: flex-start;
      }

      .label-text {
        font-size: 12px;
        font-weight: 600;
        color: #545454;
        letter-spacing: 0.429px;
      }

      .value-container {
        flex: 1;
        display: flex;
        flex-direction: column;
        gap: 8px;
      }

      .selected-items {
        display: flex;
        flex-wrap: wrap;
        gap: 4px;
        align-items: flex-start;
      }

      .selected-items-vertical {
        flex-direction: column;
        align-items: stretch;
      }

      .add-button-container {
        position: relative;
      }

      .add-button-container.full-width {
        width: 100%;
      }

      .dropdown-wrapper {
        position: relative;
        display: inline-block;
      }

      .dropdown-anchor {
        position: absolute;
        top: 0;
        left: 8px;
        width: 1px;
        height: 1px;
        opacity: 0;
        pointer-events: none;
      }

      .add-button {
        display: inline-flex;
        align-items: center;
        gap: 4px;
        padding: 7px 8px;
        background: transparent;
        border: 1px solid #008bc9;
        border-radius: 4px;
        color: #006cab;
        font-size: 12px;
        font-weight: 400;
        letter-spacing: 0.429px;
        cursor: pointer;
        transition: all 0.2s ease;
        text-decoration: none;
      }

      .add-button:hover {
        background-color: #f0f9ff;
        text-decoration: none;
      }

      .add-button:focus {
        outline: none;
        box-shadow: 0 0 0 2px rgba(0, 139, 201, 0.2);
      }

      .add-button.full-width-button {
        width: 100%;
        justify-content: center;
      }

      .add-icon {
        width: 12px;
        height: 12px;
      }

      .dropdown-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 999;
        background: transparent;
      }

      .dropdown-content {
        min-width: 200px;
        max-width: 400px;
      }

      /* Size variants */
      .size-sm {
        font-size: 11px;
      }

      .size-default {
        font-size: 12px;
      }

      .size-lg {
        font-size: 14px;
      }

      /* Disabled styles */
      .multi-select-disabled {
        opacity: 0.6;
        pointer-events: none;
        cursor: not-allowed;
      }
    `,
  ],
})
export class MultiSelectComponent implements ControlValueAccessor, OnDestroy {
  @Input() label: string = "Tags";
  @Input() value: MultiSelectItem[] = [];
  @Input() options: MultiSelectItem[] = [];
  @Input() addButtonText: string = "Add Tags";
  @Input() searchPlaceholder: string = "Search tags";
  @Input() maxWidth: string = "568px";
  @Input() orientation: MultiSelectOrientation = "horizontal";
  @Input() size: MultiSelectSize = "default";
  @Input() disabled: boolean = false;
  @Input() showAddButton: boolean = true;
  @Input() allowRemove: boolean = true;
  @Input() fullWidthButton: boolean = false;

  @Output() valueChange = new EventEmitter<MultiSelectItem[]>();

  @ContentChild("selectedItem") selectedItemTemplate?: TemplateRef<any>;
  @ViewChild("dropdownAnchor") dropdownAnchor!: ElementRef;
  @ViewChild("dropdownContent") dropdownContent!: ElementRef;

  isOpen: boolean = false;
  private destroy$ = new Subject<void>();

  // ControlValueAccessor implementation
  private onChange = (value: MultiSelectItem[]) => {};
  private onTouched = () => {};

  constructor(
    private cdr: ChangeDetectorRef,
    private elementRef: ElementRef,
  ) {}

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  // ControlValueAccessor methods
  writeValue(value: MultiSelectItem[]): void {
    this.value = value || [];
    this.cdr.markForCheck();
  }

  registerOnChange(fn: (value: MultiSelectItem[]) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
    this.cdr.markForCheck();
  }

  get availableOptions(): MultiSelectItem[] {
    return this.options.filter((option) => !option.disabled);
  }

  getContainerClasses(): string {
    const classes = ["multi-select-container"];

    classes.push(`multi-select-${this.orientation}`);
    classes.push(`size-${this.size}`);

    if (this.disabled) {
      classes.push("multi-select-disabled");
    }

    return classes.join(" ");
  }

  getSelectedItemsClasses(): string {
    const classes = ["selected-items"];

    if (this.fullWidthButton) {
      classes.push("selected-items-vertical");
    }

    return classes.join(" ");
  }

  toggleDropdown(): void {
    if (this.disabled) return;

    this.isOpen = !this.isOpen;
    this.onTouched();

    if (this.isOpen) {
      setTimeout(() => this.positionDropdown(), 0);
    }
  }

  closeDropdown(): void {
    this.isOpen = false;
    this.cdr.markForCheck();
  }

  private positionDropdown(): void {
    if (!this.dropdownAnchor || !this.dropdownContent) return;

    const anchor = this.dropdownAnchor.nativeElement;
    const dropdown = this.dropdownContent.nativeElement;
    const rect = anchor.getBoundingClientRect();

    dropdown.style.left = `${rect.left}px`;
    dropdown.style.top = `${rect.top}px`;
  }

  handleSelectionChange(event: {
    item: MultiSelectItem;
    isSelected: boolean;
  }): void {
    const { item, isSelected } = event;
    let newValue: MultiSelectItem[];

    if (isSelected) {
      // Remove item
      newValue = this.value.filter((existing) => existing.id !== item.id);
    } else {
      // Add item
      const itemExists = this.value.some((existing) => existing.id === item.id);
      if (!itemExists) {
        newValue = [...this.value, item];
      } else {
        newValue = this.value;
      }
    }

    this.updateValue(newValue);
  }

  handleCreateNew(label: string): void {
    const newItem: MultiSelectItem = {
      id: `new-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      label: label.trim(),
    };

    const newValue = [...this.value, newItem];
    this.updateValue(newValue);
    this.closeDropdown();
  }

  handleRemove(itemToRemove: MultiSelectItem): void {
    if (this.disabled || !this.allowRemove) return;

    const newValue = this.value.filter((item) => item.id !== itemToRemove.id);
    this.updateValue(newValue);
  }

  getRemoveFunction(item: MultiSelectItem): () => void {
    return () => this.handleRemove(item);
  }

  private updateValue(newValue: MultiSelectItem[]): void {
    this.value = newValue;
    this.valueChange.emit(newValue);
    this.onChange(newValue);
    this.cdr.markForCheck();
  }

  trackSelectedItem(index: number, item: MultiSelectItem): any {
    return item.id;
  }
}
